# Site settings
title: CosmoKlee
email: laurie.trichet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Australian life, programming stuff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://laurietrichet.com" # the base hostname & protocol for your site
twitter_username: Klee_CC
github_username:  laurietrichet

# Build settings
markdown: kramdown
